# Built with Jekyll 3.6.2

title:               GoyoBot
tagline:             ''
description:         ''
url:                 https://goyobot.github.io
baseurl:             ''
twitter_username:    goyobot
github_username:     goyobot

permalink: pretty
permalink: /:title/

encoding: utf-8

markdown: kramdown


collections:
  authors:           # Set the _authors directory as a collection
    output: true     # Make the author profile public

defaults:
  # Set the default layout for all authors
  - scope:
      path: _authors
    values:
      layout: user_profile
