shortname: Miembro
name: Este personaje es un misterio...
url: http://goyobot.github.io
twitter: twitter.com/goyobot
icon: assets/img/members/default.png

# Use > to write a multiline comment
aboutme: >
  "Miebro de Goyobot.
  
  Aún no tiene descripción, pero te aseguramos que toma microchips con leche para desayunar. 💪"
  
